name: Continous Deployment
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN }}
      - name: Minify JS
        uses: devatherock/minify-js@v1.0.2
        with:
          directory: 'js'
          add_suffix: false
      - name: Minify CSS
        uses: devatherock/minify-js@v1.0.2
        with:
          directory: 'css'
          add_suffix: false
      - name: Delete Uneccessary Files
        run: rm -rf coverage/ && rm -rf docs/ && rm -rf tests/
      - name: Push changes
        uses: actions-js/push@v1.2
        with:
          github_token: ${{secrets.GITHUB_TOKEN }}
          branch: 'production'
          force: true
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build Docs
        run: npm run doc
      - name: Commit and push to repo
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add autoDocs/*
          git commit -m "auto update docs"
          git push origin
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install depndencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
        run: npx semantic-release
